### ISSUE TITLE
clip.x: double value expected

### ISSUE THREAD

**Issue by sarnobat** [schnerd/chrome-headless-screenshots#16]
input
```
docker run -it -v $PWD:/var/output/ --rm chrome-headless-screenshots-app --url="http://www.eff.org"  
```
output

```
This script requires Chrome 60, however you are using version 61. The script is not guaranteed to work and you may need to modify it.
Exception while taking screenshot: { Error: Invalid parameters
    at /usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:69:28
    at Chrome.handleMessage (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:259:13)
    at WebSocket.<anonymous> (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:236:27)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (/usr/src/app/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/usr/src/app/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/usr/src/app/node_modules/ws/lib/PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:438:3)
  code: -32602,
  data: 'clip.x: double value expected; clip.y: double value expected; clip.scale: double value expected' }
```

**Comment by sarnobat** [comment]
Version info
```
Linux nuc 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stevenspiel** [comment]
I'm also having this issue on mac OS
